- Demote loader image now expect TO_BUILD number

diff --git a/images/demote-loader/Jenkinsfile b/images/demote-loader/Jenkinsfile
--- a/images/demote-loader/Jenkinsfile
+++ b/images/demote-loader/Jenkinsfile
@@ -10,7 +10,7 @@
 //
 // curl -X POST https://jenkins-fragalysis-cicd.apps.xchem.diamond.ac.uk/job/Demote%20Web%20Image/build \
 //       --user <user>:<token> \
-//       --data-urlencode json='{"parameter": [{"name":"TO_VERSION", "value":"1.2.0"}]}'
+//       --data-urlencode json='{"parameter": [{"name":"TO_BUILD", "value":"32"}]}'
 
 
 pipeline {
@@ -47,10 +47,10 @@ pipeline {
                          string(credentialsId: 'ocUserPassword', variable: 'OC_USER_PASSWORD')]) {
 
           slackSend channel: "#${SLACK_BUILD_CHANNEL}",
-                    message: "${JOB_NAME} - demoting to version ${TO_VERSION}"
+                    message: "${JOB_NAME} - demoting to build ${TO_BUILD}"
 
           // Expose the supplied parameters...
-          echo "TO_VERSION is '${TO_VERSION}'"
+          echo "TO_BUILD is '${TO_BUILD}'"
 
           // Does the version exist as a tagged image?
           // It must if we are to continue.
@@ -58,9 +58,10 @@ pipeline {
           sh "oc login ${CLUSTER_URL} -u ${OC_USER} -p ${OC_USER_PASSWORD}"
           sh "oc project ${SRC_PROJECT}"
           script {
-            IMAGE_TAG = sh(script: "oc describe is ${STREAM_NAME} | grep ^${TO_VERSION}\$ || true", returnStdout: true).trim()
+
+            IMAGE_TAG = sh(script: "oc describe is ${STREAM_NAME} | grep latest-${TO_BUILD}\$ || true", returnStdout: true).trim()
             if (IMAGE_TAG.length() == 0) {
-              error("Unable to demote the image - version '${TO_VERSION}' does not exist")
+              error("Unable to demote the image - build '${TO_BUILD}' does not exist")
             }
           }
 
@@ -68,14 +69,11 @@ pipeline {
       }
     }
 
-    stage('Demote Image') {
+    stage('Check Deployment') {
       steps {
 
-        // Tag 'AS_VERSION' as 'stable'.
-        // But, as it's used in a Job this does not result in a re-deployment.
-        // Instead we need to check that a prior instance is not running
-        // before we launch the image as a new job using the OC CLI.
-        sh "oc tag ${SRC_STREAM_IMAGE}:${TO_VERSION} ${TGT_STREAM_IMAGE}"
+        //
+        sh "oc tag ${SRC_STREAM_IMAGE}:latest-${TO_BUILD} ${TGT_STREAM_IMAGE}"
         sh "oc project ${TGT_PROJECT}"
         script {
           LOADER_RUNNING = sh(script: 'oc get jobs | grep loader | grep Running | wc -l', returnStdout: true).trim()
@@ -91,6 +89,11 @@ pipeline {
       }
       steps {
         dir('images/loader') {
+          // Tag 'TO_BUILD' as 'stable'.
+          // But, as it's used in a Job this does not result in a re-deployment.
+          // Instead we need to check that a prior instance is not running
+          // before we launch the image as a new job using the OC CLI.
+          sh "oc tag ${SRC_STREAM_IMAGE}:latest-${TO_BUILD} ${TGT_STREAM_IMAGE}"
           sh "oc delete job/fs-loader"
           sleep 4
           sh "oc process -p LOADER_NAMESPACE=${TGT_PROJECT} -p LOADER_IMAGE=${TGT_STREAM_IMAGE} -f fs-loader.yaml | oc create -f -"
