- Tweaks web job - Loader now behaves like Web (i.e. prevent repeated promotions)

diff --git a/images/promote-loader/Jenkinsfile b/images/promote-loader/Jenkinsfile
--- a/images/promote-loader/Jenkinsfile
+++ b/images/promote-loader/Jenkinsfile
@@ -21,15 +21,20 @@ pipeline {
   environment {
     // User/Registry information.
     REGISTRY_USER = 'jenkins'
-    IMAGE_NAME = 'loader-stream'
+    REGISTRY = 'docker-registry.default.svc:5000'
+    STREAM_NAME = 'loader-stream'
 
     // Source registry details
     SRC_PROJECT = 'fragalysis-cicd'
-    SRC_STREAM_IMAGE = "${SRC_PROJECT}/${IMAGE_NAME}:latest"
+    SRC_STREAM_IMAGE = "${SRC_PROJECT}/${STREAM_NAME}"
 
     // Target registry details
     TGT_PROJECT = 'fragalysis-prod'
-    TGT_STREAM_IMAGE = "${TGT_PROJECT}/${IMAGE_NAME}:stable"
+    TGT_STREAM_IMAGE = "${TGT_PROJECT}/${STREAM_NAME}:stable"
+
+    // Archive registry (on DockerHub)
+    ARCHIVE_REGISTRY = 'docker.io/xchem'
+    ARCHIVE_NAME = 'loader-image'
 
     // Slack channel for all notifications
     SLACK_BUILD_CHANNEL = 'dls-builds'
@@ -37,6 +42,9 @@ pipeline {
     // (which also go to the CI/CD channel)
     SLACK_ALERT_CHANNEL = 'dls-alerts'
 
+    // Docker hub credentials
+    DOCKER_USER = credentials('abcDockerUser')
+    DOCKER_PASSWORD = credentials('abcDockerPassword')
   }
 
   stages {
@@ -55,47 +63,81 @@ pipeline {
           echo "AS_VERSION is '${AS_VERSION}'"
 
           // Does the build exist as a tagged image?
+          // It must if we are to continue.
+          //
           sh "oc login ${CLUSTER_URL} -u ${OC_USER} -p ${OC_USER_PASSWORD}"
           sh "oc project ${SRC_PROJECT}"
           script {
-            IMAGE_TAG = sh(script: "oc describe is ${IMAGE_NAME} | grep latest-${PROMOTE_BUILD}\$ || true", returnStdout: true).trim()
+            IMAGE_TAG = sh(script: "oc describe is ${STREAM_NAME} | grep latest-${PROMOTE_BUILD}\$ || true", returnStdout: true).trim()
+            if (IMAGE_TAG.length() == 0) {
+              error("Unable to promote the build -  build '${PROMOTE_BUILD}' does not exist")
+            }
           }
           echo "IMAGE_TAG is '${IMAGE_TAG}'"
+
+          // Does the build exist as a versioned image?
+          // It must not if we are to continue.
+          script {
+            VERSION_TAG = sh(script: "oc describe is ${STREAM_NAME} | grep ^${AS_VERSION}\$ || true", returnStdout: true).trim()
+            if (VERSION_TAG.length() != 0) {
+              error("Unable to promote the build - version '${AS_VERSION}' already exists")
+            }
+          }
 
         }
       }
     }
 
-    stage('Missing Image') {
-      when {
-        expression { IMAGE_TAG.length() == 0 }
-      }
+    stage('Build Versioned Image') {
       steps {
-        script {
-          // The build number that we're meant to tag does not exist.
-          echo "OOOPS: The build number to promote (${PROMOTE_BUILD}) does not exist"
-          currentBuild.result = 'FAILURE'
+        dir('images/promote-loader') {
+
+          // Builds a new production image using the PROMOTE_BUILD image.
+          // The build stage is simply used to add addition tags.
+          // To do this (as ARG-before-FROM is not supported in buildah 1.3)
+          // we first have to re-tag the image as 'latest-0' (the FROM in our Dockerfile)
+          script {
+            TOKEN = sh(script: 'oc whoami -t', returnStdout: true).trim()
+          }
+          sh "podman login --tls-verify=false --username ${REGISTRY_USER} --password ${TOKEN} ${REGISTRY}"
+          sh "buildah pull --tls-verify=false docker://${REGISTRY}/${SRC_STREAM_IMAGE}:latest-${PROMOTE_BUILD}"
+          sh "buildah tag ${REGISTRY}/${SRC_STREAM_IMAGE}:latest-${PROMOTE_BUILD} ${SRC_STREAM_IMAGE}:latest-0"
+          sh "buildah bud --format docker --build-arg VERSION_NUMBER=${AS_VERSION} -f Dockerfile -t ${SRC_STREAM_IMAGE}:${AS_VERSION} ."
+
         }
+      }
+    }
+
+    // Push the versioned image into our local registry
+    stage('Push Image') {
+      steps {
+
+        sh "buildah push --tls-verify=false ${SRC_STREAM_IMAGE}:${AS_VERSION} docker://${REGISTRY}/${SRC_STREAM_IMAGE}:${AS_VERSION}"
+        sh "podman logout ${REGISTRY}"
+
       }
     }
 
     stage('Promote Image') {
-      when {
-        expression { IMAGE_TAG.length() > 0 }
-      }
       steps {
-        sh "oc tag ${SRC_STREAM_IMAGE}-${PROMOTE_BUILD} ${TGT_STREAM_IMAGE}"
+
+        // Tag 'latest-NNN' as 'stable'.
+        // But, as it's used in a Job this does not result in a re-deployment.
+        // Instead we need to check that a prior instance is not running
+        // before we launch the image as a new job using the OC CLI.
+        sh "oc tag ${SRC_STREAM_IMAGE}:${AS_VERSION} ${TGT_STREAM_IMAGE}"
         sh "oc project ${TGT_PROJECT}"
         script {
           LOADER_RUNNING = sh(script: 'oc get jobs | grep loader | grep Running | wc -l', returnStdout: true).trim()
         }
         echo "RUNNING=${LOADER_RUNNING}"
+
       }
     }
 
     stage('Deploy Image') {
       when {
-        expression { IMAGE_TAG.length() > 0 && LOADER_RUNNING == '0' }
+        expression { LOADER_RUNNING == '0' }
       }
       steps {
         dir('images/loader') {
@@ -112,7 +154,7 @@ pipeline {
 
     stage('Blocked Image') {
       when {
-        expression { IMAGE_TAG.length() > 0 && LOADER_RUNNING != '0' }
+        expression { LOADER_RUNNING != '0' }
       }
       steps {
         echo "A prior loader is still running (deployment is blocked)"
@@ -126,6 +168,17 @@ pipeline {
           // Here we just set the build status to UNSTABLE.
           currentBuild.result = 'UNSTABLE'
         }
+      }
+    }
+
+    // Archive the versioned image (to DockerHub)
+    stage('Archive Image') {
+      steps {
+
+        sh "podman login --username ${DOCKER_USER} --password ${DOCKER_PASSWORD} docker.io"
+//        sh "buildah push --tls-verify localhost/${SRC_STREAM_IMAGE}:${AS_VERSION} docker://${ARCHIVE_REGISTRY}/${ARCHIVE_NAME}:${AS_VERSION}"
+        sh "podman logout docker.io"
+
       }
     }
 
